### ISSUE TITLE
MapInfoWindow에 style 적용 어떻게 하는 걸까요?

### ISSUE THREAD

**Issue by hoyuenkim** [JaeSeoKim/react-kakao-maps-sdk#11]
<MapMarker
                  position={{
                    lat: result.location.coordinates[1],
                    lng: result.location.coordinates[0],
                  }}
                  infoWindowOptions={{
                    style: { textAlign: 'center' },
                    removable: true,
                  }}
                  onClick={() => router.push(`/menu/${result.id}`)}
                >
                  <>
                    <div style={{ display: 'inline', textAlign: 'center' }}>
                      {result.name}
                    </div>
                  </>
                </MapMarker>

나름 이런저런 시도를해봤는데... infoWindowOptions에서 style 옵션이 안먹힙니다.

윈도우 폭을 inline-block 하고 싶어요...

**Comment by JaeSeoKim** [comment]
v2.0.0 버전 부터는 `InfoWindow` 내부로직에서 사용하던 `div` 객체를 `props` 전달을 통해 스타일링 사용하는 것이 아닌, `children` 부분으로 넣은 것이 바로 `infoWindow`의 root로 들어 가도록 수정 작업 중입니다.
