### ISSUE TITLE
Cannot read properties of undefined (reading 'Places')

### ISSUE THREAD

**Issue by sunwoo0706** [JaeSeoKim/react-kakao-maps-sdk#16]
`nextJS` 에서 Sample 키워드로 장소검색하기 부분을 코딩하던 중에 아래와 같이 오류가 발생했습니다.

<img width="957" alt="스크린샷 2022-05-22 오후 6 07 56" src="https://user-images.githubusercontent.com/60869316/169687905-77e1eebc-a83a-4d6b-beac-5994d28c885c.png">
 
아래는 `_app.tsx` 코드입니다.

```ts
import React from 'react';
import type { AppProps } from 'next/app';
import Script from 'next/script';

import { GlobalStyle } from 'shared/GlobalStyle';

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Script
        src={`//dapi.kakao.com/v2/maps/sdk.js?appkey=${process.env.mapApiKey}&libraries=services,clusterer&autoload=false`}
        strategy="beforeInteractive"
      />
      <GlobalStyle />
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
```

무엇이 문제일까요..

**Comment by JaeSeoKim** [comment]
https://apis.map.kakao.com/web/documentation/#services_Places

이 문제는 해당 라이브러리의 문제가 아니며, 카카오 공식 문서를 확인하시면 `new kakao.maps.services.Places()` 로 사용하는 것으로 안내되어 있는 걸로 알고 있습니다.

kakao map api는 `kakao` 전역 객체 내부에 선언되어 있으므로 사용시에 주의 하셔야 합니다.

**Comment by sunwoo0706** [comment]
아 넵 공식문서도 찾아 링크도 달아주시고 신경써주셔서 정말 감사드립니다!
