### ISSUE TITLE
마커 이미지 border-radius

### ISSUE THREAD

**Issue by restareaByWeezy** [JaeSeoKim/react-kakao-maps-sdk#22]
![image](https://user-images.githubusercontent.com/64529155/172668175-19f36527-1bac-4e76-8205-ea574f88639a.png)
![image](https://user-images.githubusercontent.com/64529155/172668448-02dade00-c9cf-474c-be2a-85b8a41c3354.png)

marker 컴포넌트에 style prop이 없는데 혹시 border-radius를 주는 방법이 있을까요?

**Comment by JaeSeoKim** [comment]
[kakao-map-api 마커 공식 문서](https://apis.map.kakao.com/web/documentation/#Marker)

해당 문서를 확인해보시면 마커 객체는 `dom` 객체를 제어하는 수단이 없습니다. 따라서 React에서 사용하기 쉽게 만든 wrapper 라이브러리이므로 React에서 사용되는 기능 이외에 공식 기능에서 제공하지 않는 기능은 제공 되지 않습니다.

그리고 해당 부분에 대해서는 dom에 스타일링 하는 것이 아닌 Marker image를 수정하여 `radius` 를 주는 것이 적합해보입니다.

**Comment by restareaByWeezy** [comment]
답변 감사드립니다!!
