### ISSUE TITLE
`react@18` 버전 `peerDependencies` 추가

### ISSUE THREAD

**Issue by Sn-Kinos** [JaeSeoKim/react-kakao-maps-sdk#26]
`react@17` 기반 프로젝트를 `react@18` 로 마이그레이션 하던 중에 `peerDependencies` `warning` 이 표시되어서 버전 대응을 하려고 하는데 괜찮을까요?

**Comment by JaeSeoKim** [comment]
문제 없습니다. `peerDenedencies` 관련 의존성 문제는 빠른 시일 내에 해결하여 배포 하도록 하겠습니다.
현재 군 입대를 한 상태여서 유지보수가 지연될 수 있습니다.
