### ISSUE TITLE
Polyline 관련 문의

### ISSUE THREAD

**Issue by zzzl-523** [JaeSeoKim/react-kakao-maps-sdk#27]
안녕하세요. 좋은 라이브러리 감사합니다.
다름이 아니라, Polyline 컴포넌트 사용시 맵을 움직일 때 line이 따로 움직이는 현상이 발생하는데 혹시 현재 어떤 오류가 있는 것인가요?

**Comment by JaeSeoKim** [comment]
혹시 해당 오류를 확인할 수 있는 예시를 올려주실 수 있나요? 현재 군대에 있어서 개발환경을 직접 구축하여 테스트 하기에는 무리가 있습니다 ㅠ...

가능하시다면 [CodeSandBox](codesandbox.io)와 같은 서비스를 이용하여 링크 달아주시면 감사하겠습니다.

**Comment by zzzl-523** [comment]
CodeSandBox로 예시를 만들어봤습니다.
onCenterChanged를 활용하면 문제가 생기는 것 같습니다!
https://codesandbox.io/s/spring-breeze-75l126?file=/src/App.js

**Comment by JaeSeoKim** [comment]
이 부분은 제가 해당 라이브러리에서 해결하기 힘든 영역인 것 같습니다.

임시로 해결 할 수 있는 방법을 이야기 해드리면, `onDragEnd` 이벤트를 활용하여 드래그 이벤트가 종료이후 `Center` 정보를 받아오는게 좋아보입니다.

추가적으로 만약 center를 변경하게 되면 그때 알맞게 State를 최신화 하는게 좋아 보입니다.!

**Comment by zzzl-523** [comment]
앗 그렇군요..
일단 추천해주신 방법으로 충분히 해결할 수 있을 것 같습니다.
빠르고 좋은 답변 감사합니다!!
