### ISSUE TITLE
클러스터 위치를 얻어올수 있을까요?

### ISSUE THREAD

**Issue by Rimririn** [JaeSeoKim/react-kakao-maps-sdk#29]
안녕하세요 지금 너무 잘쓰고 있는데 몇가지 궁금한점이 있어서 문의드립니다.

<MarkerClusterer
          averageCenter={true} // 클러스터에 포함된 마커들의 평균 위치를 클러스터 마커 위치로 설정

이렇게 설정하면 클러스터가 마커들의 평균 위치로 오는데 이 위치를 알고 싶습니다. 

그리고 클러스터 위치에 따라서 텍스트를 다르게 하고 싶은데 마커 갯수 말고 위치 별로 텍스트를 설정할 수 있는 방법이 있을까요?

**Comment by JaeSeoKim** [comment]
해당 라이브러리는 KakaoMap API를 React에서 사용하기 쉽게 랩핑한 라이브러리이므로, 기존에 추가적인 기능들은 따로 카카오측에 문의 하시는게 좋을 것 같습니다.
https://devtalk.kakao.com/c/map-api/101

현재 상황에서는 직접 클러스터링에 대한 알고리즘을 구축하여 커스텀 하는 방법 밖에 없어 보입니다....
