### ISSUE TITLE
[지도에 컨트롤 올리기] 관련해서...

### ISSUE THREAD

**Issue by Jtree03** [JaeSeoKim/react-kakao-maps-sdk#3]
커스텀 해서 만드는 것을 확인 하였는데 옵셔널하게 순정 버전 컨트롤 사용할 수 있게 하면 좋지 않을까요?

아래 커스텀, 순정 차이 첨부합니다.

### 커스텀

<img width="165" alt="스크린샷 2022-01-08 오전 11 00 16" src="https://user-images.githubusercontent.com/20152376/148627282-ee4cd2ff-21db-440e-99c1-f3f8f7d743fd.png">

[해당 커스텀 Doc](https://react-kakao-maps-sdk.jaeseokim.dev/docs/sample/map/addMapControl)

### 순정

<img width="126" alt="스크린샷 2022-01-08 오전 11 00 28" src="https://user-images.githubusercontent.com/20152376/148627296-8d72c1e6-1dc6-4b06-b1cf-4b3b7c024029.png">

[순정 Doc](https://apis.map.kakao.com/web/sample/addMapControl/)

**Comment by JaeSeoKim** [comment]
Sample 예시 코드를 커스텀 컨트롤 추가예제로 작성 했어야 했는데 실수로 잘못 작성되어 있었네요! 해당 부분 수정해서 반영하도록 하겠습니다.

해당 예시 코드는 제공되는 `ZoomControl` , `MapTypeControl` 컴포넌트를 이용하여 구현이 가능합니다.

**Comment by Jtree03** [comment]
아하 기능은 있는데 예제가 잘못되어 있던거군요.

빠른 확인 감사합니다~

**Comment by JaeSeoKim** [comment]
5d0d6df7905c8d6348d6bd197fc6d83b2d0f50ea 문서 수정 하였습니다! 배포 진행중이니 나중에 한번 확인해주세요~!

**Comment by JaeSeoKim** [comment]
[지도에 컨트롤 올리기](https://react-kakao-maps-sdk.jaeseokim.dev/docs/sample/map/addMapControl)

[지도에 사용자 컨트롤 올리기](https://react-kakao-maps-sdk.jaeseokim.dev/docs/sample/map/addMapCustomControl)
