### ISSUE TITLE
동작하지 않습니다.

### ISSUE THREAD

**Issue by Siwoo4u** [JaeSeoKim/react-kakao-maps-sdk#30]
리액트 샘플프로젝트를 새로 만들어 appkey는 index.html에 삽입하여주고 아래와 같이 소스 작성후 테스트 해보았는데
페이지가 무한로딩중이고 아무것도 로드되지 않습니다.

혹시 샘플 프로젝트를 생성해서 아무것도 없는 상태에서 설치후 테스트 해봐주실수있을까요?

//map.js

import React from 'react';
const Map = () => {
   
    return (
        <Map // 지도를 표시할 Container
            center={{
                // 지도의 중심좌표
                lat: 33.450701,
                lng: 126.570667,
            }}
            style={{
                // 지도의 크기
                width: "100%",
                height: "450px",
            }}
            level={3} // 지도의 확대 레벨
        />
      )
  };
  
  export default Map;

**Comment by JaeSeoKim** [comment]
해당 설명으로는 도움을 줄 수 있는 부분이 없습니다. 어떤 개발 환경인지, 또한 Console에서 어떠한 에러가 발생하는지, Kakao Map API가 정상적으로 로드가 되었는지 등, 한번 확인 후 이슈를 상세하게 달아주시길 부탁드리겠습니다...

현재 군 입영을 한 상황이여서 직접 개발 환경을 간단하게 만들어 테스트 하기에는 어려움이 있습니다....

**Comment by Siwoo4u** [comment]
원인은 리액트 버전 문제였습니다 리액트가 18버전으로 업데이트 되면서 문법이 바뀌었는데 그것이 원인이네요
