### ISSUE TITLE
기본  Div 네이티브 이벤트가 타입이 맞지 않습니다.

### ISSUE THREAD

**Issue by FrontLeejonghun** [JaeSeoKim/react-kakao-maps-sdk#35]
![스크린샷 2022-10-21 오후 2 42 15](https://user-images.githubusercontent.com/67212771/197121265-beea3032-ac0b-4517-a430-716302840564.png)
![스크린샷 2022-10-21 오후 2 45 20](https://user-images.githubusercontent.com/67212771/197121637-c757af52-ce63-49d1-b287-2b2530688f0c.png)

기본 div El 에 잡힌 Attribute 의 속성이 Map 에 선언된 제네릭 타입과 합쳐져서, 위와 같은 타입 에러가  발생 합니다.
해당 타입을 제거 하고 사용이 가능한데, 이때 해당 아래의 Omit 으로 뺀 이벤트를 사용하려면 어떤 방식으로 사용을 해야하나요?
혹은 커스텀 타입을 만들어서 써야하는건지 궁금합니다.

다른분들의 이슈에서는 발생되는 원인이 아닌거 같아 이슈를 남기는점 양해 부탁드립니다.

`    "next": "^12.2.5",
    "react": "18.1.0",
    "typescript": "^4.4.3"
    "react-kakao-maps-sdk": "^1.1.4",
`

``` TS interface Props
  extends Omit<
    MapProps,
    | 'onClick'
    | 'onDoubleClick'
    | 'onRightClick'
    | 'onMouseMove'
    | 'onDragStart'
    | 'onDrag'
    | 'onDragEnd'
  > {
  children?: ReactNode;
}

**Comment by JaeSeoKim** [comment]
현재 군복무중이여서 자세한 오류 환경을 구현하는 부분에 제한이 있습니다. 혹시 codesandbox와 같은 서비스를 이용해서 해당 환경을 구현해주실 수 있을까요.?

**Comment by FrontLeejonghun** [comment]
@JaeSeoKim 
https://codesandbox.io/p/sandbox/quizzical-andras-1ztiqf
감사합니다.
app.tsx에 script 구성 해놨고, 
index.tsx에서 onClick 및    | 'onClick'
    | 'onDoubleClick'
    | 'onRightClick'
    | 'onMouseMove'
    | 'onDragStart'
    | 'onDrag'
    | 'onDragEnd' 에 에러가 발생합니다.

**Comment by JaeSeoKim** [comment]
확인해보니,, 타입에 대해서 잘못 정의 하고 사용하고 있었던 부분이 있었습니다 ㅠㅠ
확실하게 테스트를 진행 후 배포를 해야 하는데 군대에 있다는 핑계로 나태하게 작성하고 작동하겠지 라는 마음으로 배포한 것 같습니다...

일단 타입 오류는 모두 잡았습니다..!

혹시 가능하시다면 [1.1.5-beta](https://www.npmjs.com/package/react-kakao-maps-sdk/v/1.1.5-beta) 버전으로 테스트 가능하실까요..?

https://codesandbox.io/p/sandbox/epic-villani-xnwfku

**Comment by FrontLeejonghun** [comment]
@JaeSeoKim 확인했습니다 :) 
다른 on* 메소드들은 기존 div Attribute Type 에 해당되지 않고, 
위 on* 메소드들은 기존 Attirbute에 해당되는 Type 이라 났던 에러인가보군요..

빠른 리뷰 감사드리며, 혹시 프로덕션은 언제쯤 반영이 될 예정인지 여쭤봐도 될까요?

**Comment by JaeSeoKim** [comment]
@FrontLeejonghun 어제 바로 해드리고 싶었지만 연등시간이 종료되어서 오늘 점심 이전에 프로덕션으로 배포해드리겠습니다.!

**Comment by JaeSeoKim** [comment]
[1.1.5](https://www.npmjs.com/package/react-kakao-maps-sdk/v/1.1.5) 버전 배포 완료 했습니다!
