### ISSUE TITLE
모바일 환경에서 마커, 폴리라인 사용

### ISSUE THREAD

**Issue by nonjee888** [JaeSeoKim/react-kakao-maps-sdk#36]
안녕하세요. 연락드린 노은지입니다.
현재 PC 환경에서는 마커와 폴리라인 사용에 문제가 없으나 모바일 환경에서는 이용에 제한이 있습니다. 
피드백 주시면 감사하겠습니다.
https://codesandbox.io/p/github/nonjee888/igo_FrontEnd/master?file=%2Fsrc%2Fcomponents%2Fpost%2FPostKakaoMap.jsx

**Comment by JaeSeoKim** [comment]
해당 문제는 kakao-map API에서 제공되는 문제 입니다.

현재 모바일 환경을 고려하고 있는 것으로 보이는데, Drawing Library의 경우 모바일에 친화적인 API가 아닌 것 같습니다.
공식 문서와 함께 제가 구현한 react-kakao-maps-sdk 에서도 모바일에서는 기능이 정상적으로 동작 하지 않는 것을 볼 수 있습니다.
 - 모바일에서 마커 생성 반응 X,
 - PolyLine 그리기 및 기타 작업을 진행하는 데에 화면에 표시되는 크기가 작아 작업의 불편이 있음, (당연한 부분으로 모바일 디바이스는 mouse hover에 대한 부분을 캐치 할 수 있는 부분이 없습니다.)
 
https://apis.map.kakao.com/web/sample/basicDrawingLibrary/
https://react-kakao-maps-sdk.jaeseokim.dev/docs/sample/library/basicDrawingLibrary

해당 기능을 사용하신다고 하면 아래의 샘플을 참고 하여 해당 Drawing Libary와 유사한 기능을 모바일 UX에 최적화 하여 직접 구현 하는 것이 좋아 보입니다.

EX) 현재 구현 방식에서는 클릭과 좌클릭으로 구현이 되어 있지만 모바일의 경우 화면에 추가적인 버튼을 추가하여 종료 기능을 추가 한다거나, 아니면 여러가지의 ToolBox를 구현하여 화면상에 같이 배치
https://react-kakao-maps-sdk.jaeseokim.dev/docs/sample/overlay/calculatePolylineDistance

**Comment by JaeSeoKim** [comment]
간단하게 샘플 예시 만들어 봤으니 한번 최적의 모바일 UX를 고민해서 기능을 구현해보세요!

https://codesandbox.io/s/cocky-dawn-j7dwcf?file=/src/App.tsx

**Comment by nonjee888** [comment]
바쁘신 와중에 시간내어 주신 점 감사드립니다!! 아 kakao-map API쪽 이슈군요... 정말 감사드립니다. 보내주신 codes and box 링크 참고하여 기능 구현 해 보도록 하겠습니다. 샘플 예시까지 만들어 주시고, 방향 잡는데 도움이 정말 많이 되었습니다 :) 감사합니다.
