### ISSUE TITLE
더블클릭시 지도확대 안되게 가능할까요 ?

### ISSUE THREAD

**Issue by jooyong-boo** [JaeSeoKim/react-kakao-maps-sdk#38]
커스텀 오버레이 클릭시 리스트가 나오게 하고있는데 짦은 간격으로 클릭시 자꾸 확대가 되네요 ㅠㅠ

**Comment by JaeSeoKim** [comment]
라이브러리 문서와 함께 Kakao Map API 문서를 함께 확인 해주시길 부탁드리겠습니다.
`disableDoubleClickZoom` Props를 활용하시면 됩니다.!

https://react-kakao-maps-sdk.jaeseokim.dev/docs/api/types/MapProps

https://apis.map.kakao.com/web/documentation/

**Comment by jooyong-boo** [comment]
앗.. 저기 있었군요.. 문서를 제대로 안본 제 잘못입니다 ㅜㅜ
감사합니다!
