### ISSUE TITLE
[TS] 타입스크립트에서 작업시 예제에 useState 타입이 적혀있으면 좋을 것 같습니다!

### ISSUE THREAD

**Issue by rkskekzzz** [JaeSeoKim/react-kakao-maps-sdk#4]
<img width="1613" alt="image" src="https://user-images.githubusercontent.com/57925497/152907817-a19d075a-07d9-465c-b218-97c2db2e9191.png">

아래는 카테고리로 검색하기 예제 코드인데 setMap호출할 때 타입에러가 발생합니다

```
function(){
  const [info, setInfo] = useState()
  const [markers, setMarkers] = useState([])
  const [map, setMap] = useState()

  ...
}
```

**Comment by JaeSeoKim** [comment]
docs 문서 예시에 type관련 안내 주석을 추가하도록 수정하겠습니다! 이슈 감사합니다~!

**Comment by JaeSeoKim** [comment]
일단 위의 경우에는 다음 아래와 같이 type 정의를 하여 사용을 하면 됩니다.

```tsx
function(){
  ...
  const [map, setMap] = useState<kakao.maps.Map>()
  ...
}
```
