### ISSUE TITLE
"CustomOverlay1Style" 모듈을 불러오지 못하는 이슈

### ISSUE THREAD

**Issue by sak5010** [JaeSeoKim/react-kakao-maps-sdk#40]
Sample 탭에서 "커스텀 오버레이생성하기1"을 진행중입니다.  <br />
라이브 에디터에 있는 코드는 다음과 같습니다.
```js
function(){
  return (
    <>
      <CustomOverlay1Style />
      <Map // 지도를 표시할 Container
        center={{
          // 지도의 중심좌표
          lat: 33.450701,
          lng: 126.570667,
        }}
        style={{
          // 지도의 크기
          width: "100%",
          height: "450px",
        }}
        level={3} // 지도의 확대 레벨
      >
        <CustomOverlayMap // 커스텀 오버레이를 표시할 Container
          // 커스텀 오버레이가 표시될 위치입니다
          position={{
            lat: 33.450701,
            lng: 126.570667,
          }}
        >
          {/* 커스텀 오버레이에 표시할 내용입니다 */}
          <div className="label" style={{color: "#000"}}>
            <span className="left"></span>
            <span className="center">카카오!</span>
            <span className="right"></span>
          </div>
        </CustomOverlayMap>
      </Map>
    </>
  )
}
```
<br/> 
위 코드에서 CustomOverlay1Style을 사용하고 있습니다. <br/>
그래서 `import { CustomOverlay1Style } from 'react-kakao-maps'sdk';`로 불러오려고 했지만 <br/>
`"message": "Module '\"react-kakao-maps-sdk\"' has no exported member 'CustomOverlay1Style'.",` <br/>
에러가 뜹니다. 어떻게 해결해야할까요?

**Comment by JaeSeoKim** [comment]
해당 코드는 샘플일 뿐 실제 구현 부분은 라이브러리 API를 확인 하시길 바랍니다. 해당 컴포넌트는 라이브러리에서 제공하는 것이 아닌 샘플 오버레이 스타일링을 위한 css 주입 컴포넌트 입니다. 해당 css 내용이 궁금하시다면 원본 카카오 문서를 확인하시거나 내부 코드를 확인 하는 것을 권장 드립니다.

https://apis.map.kakao.com/web/sample/customOverlay1/

https://github.com/JaeSeoKim/react-kakao-maps-sdk/blob/main/docs/src/theme/ReactLiveScope/index.tsx#L100

**Comment by sak5010** [comment]
아하! 링크 주신 코드 보고 이해했습니다 빠른 답변 감사합니다 :)
