### ISSUE TITLE
CustomOverlayMap 등록시 className 에러

### ISSUE THREAD

**Issue by seongsoo96** [JaeSeoKim/react-kakao-maps-sdk#42]
<CustomOverlayMap
              position={center}
              className={`MapWalker ${getAngleClassName(pan)}`}
              yAnchor={1}
            >
              <div className={`angleBack`}></div>
              <div className={"figure"}></div>
            </CustomOverlayMap>

https://react-kakao-maps-sdk.jaeseokim.dev/docs/sample/roadview/moveRoadview 이부분 보고 따라했는데
className에서 에러가 납니다.

TS2322: Type '{ children: Element[]; position: { lat: number; lng: number; }; className: string; yAnchor: number; }' is not assignable to type 'IntrinsicAttributes & CustomOverlayMapProps & { children?: ReactNode; } & RefAttributes<CustomOverlay>'.
  Property 'className' does not exist on type 'IntrinsicAttributes & CustomOverlayMapProps & { children?: ReactNode; } & RefAttributes<CustomOverlay>'.
    70 |             <CustomOverlayMap
    71 |               position={center}
  > 72 |               className={`MapWalker ${getAngleClassName(pan)}`}
       |               ^^^^^^^^^
    73 |               yAnchor={1}
    74 |             >
    75 |               <div className={`angleBack`}></div>

임의로 CustomOverlayMap.d.ts에
![스크린샷 2023-01-03 오후 5 04 19](https://user-images.githubusercontent.com/71514285/210319242-345818ce-11e6-4bcc-ba95-93468b6febed.png)
이 부분을 아래와 같이 추가해주면 에러는 해결이 됩니다.
![스크린샷 2023-01-03 오후 5 04 47](https://user-images.githubusercontent.com/71514285/210319295-f680f5b5-0f9d-4209-82ae-3fb7717f2e9d.png)

이렇게 해결하는게 맞는지 궁금합니다.

**Comment by JaeSeoKim** [comment]
#41 이슈를 참고하시면 좋을 것 같습니다.! 문서를 잘못 작성한 부분이 있어서 발생한 문제 입니다 ;;

문서를 수정하여 반영을 해야 하는데, 군대에 있다보니 컴퓨터로 작업을 하기 힘든 부분이 있어서 양해 부탁드립니다 ㅠㅠ

**Comment by seongsoo96** [comment]
감사합니다 잘 해결 되었습니다 ^^
