### ISSUE TITLE
웹 모바일 환경

### ISSUE THREAD

**Issue by daeeop** [JaeSeoKim/react-kakao-maps-sdk#49]
웹 모바일 환경 에서 지도가 나타나지 않습니다. 데스크탑 에서 화면 사이즈를 줄이면 잘 나오는데 스마트폰 으로 접속 하면 나오지가 않네요..

**Comment by JaeSeoKim** [comment]
해당 설명만으로는 오류를 식별하기 어렵습니다. 해당 증상을 구현할 수 있는 환경을 web ide 플랫폼을 이용하여 제공해주시면 감사하겠습니다. 또한 현재 군 복무중에 있어 답변이 지연될 수 있습니다.

**Comment by JaeSeoKim** [comment]
@daeeop
오랫동안 업데이트가 없는 이슈여서, Close 처리 합니다. 추가로 이야기를 나눌 부분이 있다면 언제든지 Open 해주세요.!
