### ISSUE TITLE
대량의 데이터 들어올 시, 카카오 맵 로드 안됨

### ISSUE THREAD

**Issue by ygh0627** [JaeSeoKim/react-kakao-maps-sdk#50]
안녕하세요.
우선 사용하기 편하게 리액트에 맞춘 라이브러리 만들어주셔서 감사합니다. 도움 정말 많이 받았습니다.
헌데, 사용하던 중 문제가 생겨 질문 드립니다.
문제상황은 다음과 같습니다.

1. 들어오는 데이터(지도에 표시되는 데이터)가 적은 경우에는 문제가 없음.
2. 들어오는 데이터가 큰 경우(이번 케이스 : 배열 길이 1,000), 다음과 같은 경고문구가 1초에 2번정도 간격으로 콘솔에 찍히면서 지도를 렌더링하고 있는 screen으로의 이동이 아예 불가함.

[Violation] Added non-passive event listener to a scroll-blocking <some> 이벤트. Consider marking event handler as 'passive' to make the page more responsive. See <URL>

답변해주시면 감사하겠습니다.

**Comment by JaeSeoKim** [comment]
현재 군복무중에 있어서 해당 환경을 직접 테스트 하기가 힘든 환경에 있습니다. 해당 오류가 발생하는 환경을 codesandbox와 같은 플랫폼을 이용하여 공유 해주실 수 있을까요?

**Comment by JaeSeoKim** [comment]
@ygh0627 
오랫동안 업데이트가 없는 이슈여서, Close 처리 합니다. 추가로 이야기를 나눌 부분이 있다면 언제든지 Open 해주세요.!
