### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'OverlayType'

### ISSUE THREAD

**Issue by swjo207** [JaeSeoKim/react-kakao-maps-sdk#51]
Next JS (13.2.4)  마이그레이션 하다가, 우연히 발견하게 되었습니다. 

DrawingManager를 사용해야 하는데, 계속 문제에 부딪쳐서 한번 여쭤보고자 합니다. 
https://react-kakao-maps-sdk.jaeseokim.dev/docs/sample/library/basicDrawingLibrary
샘플을 /app/map/page.tsx 에서 복사해서 띄워 보는데, 
**TypeError: Cannot read properties of undefined (reading 'OverlayType')**
타입 에러가 뜨고 진전이 없습니다. 

tsconfig.json 파일에, 

"types": [
      "kakao.maps.d.ts"
    ]

가 설정되어 있으며, vscode 에디터에서도 OverlayType이 레퍼런싱이 되는 걸로 봐서는 문제가 없을 것 같은데, 

-----
테스트한 소스는 다음과 같습니다. 

'use client'
import Script from "next/script"
import { useRef } from "react"
import { Map, DrawingManager } from "react-kakao-maps-sdk"

declare global {
    interface Window {
        kakao: any;
    }
}

let map_src = `//dapi.kakao.com/v2/maps/sdk.js?appkey=${process.env.NEXT_PUBLIC_KAKAO_MAP_API_KEY}&autoload=false&libraries=drawing,services,clusterer`;

export default function MapEdit()
{
    // ref 객체를 통해 kakao.maps.drawng.DrawingManager 객체를 전달 받아 사용합니다.
    // 또한 TypeScript를 사용하기 떄문에 전달 받는 DrawingManager에서 사용하는 OverlayType에 대해서 정의해야 합니다.
    const managerRef =
        useRef<
            kakao.maps.drawing.DrawingManager<
                | kakao.maps.drawing.OverlayType.ARROW
                | kakao.maps.drawing.OverlayType.CIRCLE
                | kakao.maps.drawing.OverlayType.ELLIPSE
                | kakao.maps.drawing.OverlayType.MARKER
                | kakao.maps.drawing.OverlayType.POLYLINE
                | kakao.maps.drawing.OverlayType.RECTANGLE
                | kakao.maps.drawing.OverlayType.POLYGON
            >
        >(null)

    function selectOverlay(type: kakao.maps.drawing.OverlayType) {
        const manager = managerRef.current
        manager?.cancel()
        manager?.select(type)
    }

    return (
        <>
            <Script
                src={map_src}
                strategy="beforeInteractive"
            // onLoad={() => {
            //   console.log("카카오맵 스크립트 로딩 완료. ~~~~~");
            // }}
            // onReady={() => {
            //   console.log("카카오맵 스크립트 준비 완료. ~~~~~");
            // }}
            />
            <Map
                center={{
                    // 지도의 중심좌표
                    lat: 33.450701,
                    lng: 126.570667,
                }}
                style={{
                    width: "100%",
                    height: "450px",
                }}
                level={3} // 지도의 확대 레벨
            >
                <DrawingManager
                    ref={managerRef}
                    drawingMode={[
                        kakao.maps.drawing.OverlayType.ARROW,
                        kakao.maps.drawing.OverlayType.CIRCLE,
                        kakao.maps.drawing.OverlayType.ELLIPSE,
                        kakao.maps.drawing.OverlayType.MARKER,
                        kakao.maps.drawing.OverlayType.POLYLINE,
                        kakao.maps.drawing.OverlayType.RECTANGLE,
                        kakao.maps.drawing.OverlayType.POLYGON,
                    ]}
                    guideTooltip={["draw", "drag", "edit"]}
                    markerOptions={{
                        // 마커 옵션입니다
                        draggable: true, // 마커를 그리고 나서 드래그 가능하게 합니다
                        removable: true, // 마커를 삭제 할 수 있도록 x 버튼이 표시됩니다
                    }}
                    polylineOptions={{
                        // 선 옵션입니다
                        draggable: true, // 그린 후 드래그가 가능하도록 설정합니다
                        removable: true, // 그린 후 삭제 할 수 있도록 x 버튼이 표시됩니다
                        editable: true, // 그린 후 수정할 수 있도록 설정합니다
                        strokeColor: "#39f", // 선 색
                        hintStrokeStyle: "dash", // 그리중 마우스를 따라다니는 보조선의 선 스타일
                        hintStrokeOpacity: 0.5, // 그리중 마우스를 따라다니는 보조선의 투명도
                    }}
                    rectangleOptions={{
                        draggable: true,
                        removable: true,
                        editable: true,
                        strokeColor: "#39f", // 외곽선 색
                        fillColor: "#39f", // 채우기 색
                        fillOpacity: 0.5, // 채우기색 투명도
                    }}
                    circleOptions={{
                        draggable: true,
                        removable: true,
                        editable: true,
                        strokeColor: "#39f",
                        fillColor: "#39f",
                        fillOpacity: 0.5,
                    }}
                    polygonOptions={{
                        draggable: true,
                        removable: true,
                        editable: true,
                        strokeColor: "#39f",
                        fillColor: "#39f",
                        fillOpacity: 0.5,
                        hintStrokeStyle: "dash",
                        hintStrokeOpacity: 0.5,
                    }}
                    arrowOptions={{
                        draggable: true, // 그린 후 드래그가 가능하도록 설정합니다
                        removable: true, // 그린 후 삭제 할 수 있도록 x 버튼이 표시됩니다
                        editable: true, // 그린 후 수정할 수 있도록 설정합니다
                        strokeColor: "#39f", // 선 색
                        hintStrokeStyle: "dash", // 그리중 마우스를 따라다니는 보조선의 선 스타일
                        hintStrokeOpacity: 0.5, // 그리중 마우스를 따라다니는 보조선의 투명도
                    }}
                    ellipseOptions={{
                        draggable: true,
                        removable: true,
                        editable: true,
                        strokeColor: "#39f",
                        fillColor: "#39f",
                        fillOpacity: 0.5,
                    }}
                />
            </Map>
            <div
                style={{
                    display: "flex",
                    gap: "8px",
                }}
            >
                <button
                    onClick={(e) => {
                        selectOverlay(kakao.maps.drawing.OverlayType.POLYLINE)
                    }}
                >
                    선
                </button>
                <button
                    onClick={(e) => {
                        selectOverlay(kakao.maps.drawing.OverlayType.ARROW)
                    }}
                >
                    화살표
                </button>
                <button
                    onClick={(e) => {
                        selectOverlay(kakao.maps.drawing.OverlayType.CIRCLE)
                    }}
                >
                    원
                </button>
                <button
                    onClick={(e) => {
                        selectOverlay(kakao.maps.drawing.OverlayType.MARKER)
                    }}
                >
                    마커
                </button>
                <button
                    onClick={(e) => {
                        selectOverlay(kakao.maps.drawing.OverlayType.POLYGON)
                    }}
                >
                    다각형
                </button>
                <button
                    onClick={(e) => {
                        selectOverlay(kakao.maps.drawing.OverlayType.RECTANGLE)
                    }}
                >
                    사각형
                </button>
            </div>
        </>
    )
}

**Comment by JaeSeoKim** [comment]
마지막 세번째 방법에 대해서 코드를 다시확인 해본 결과 내부적인 값이 변경될 일이 없을 것 같아서 해당 부분 작업하여, 추후 다음 버전에 반영하도록 하겠습니다.

https://tsplay.dev/W4bRaN
