### ISSUE TITLE
API Document 에 browser cache 초기화 관련 매뉴얼 제공

### ISSUE THREAD

**Issue by JeHwanYoo** [JaeSeoKim/react-kakao-maps-sdk#53]
https://devtalk.kakao.com/t/api/120733/22?u=lea.ju

지도 서비스 호출 시, 정상적으로 URL 을 등록 했음에도 불구, 캐시 때문에 CORS 문제가 발생 할 수 있습니다. 

엄청 크리티컬한 이슈는 아니지만, Kakao Maps API 를 사용하는 사용자들에게 도움이 될 것 같습니다.

![Screenshot 2023-08-03 at 9 01 51 AM](https://github.com/JaeSeoKim/react-kakao-maps-sdk/assets/13535954/9e14cc47-89de-440c-a97a-fdba33366523)

**Comment by JaeSeoKim** [comment]
해당 라이브러리는 React에서 KakaoMap를 사용하기 편하도록 만든 비공식 라이브러리입니다.

해당 문제는 kakao측에서 캐시설정을 잘못하여 발생한 문제 같으며, 또한 일시적인 것으로 보여 비공식 라이브러리에서 해당 안내를 제공하는 것은 좋아보이지 않습니다.
