### ISSUE TITLE
Could not find a declaration file for module 'react-kakao-maps-sdk'.

### ISSUE THREAD

**Issue by choijeongon** [JaeSeoKim/react-kakao-maps-sdk#54]
next.js 13와 typescript에서 작업 중인데

![image](https://github.com/JaeSeoKim/react-kakao-maps-sdk/assets/79705809/d918bd18-cfca-4c2c-b444-0a239789067f)

package.json에 "kakao.maps.d.ts"도 추가해주고
tsconfig.json에 compilerOptions -> "types": ["kakao.maps.d.ts"]을 추가해줘도
해당 에리거 발생하네요..

혹시 해결 방법 있을까요?

**Comment by JaeSeoKim** [comment]
@choijeongon 확인 해보니, [ECMAScript Modules](https://www.typescriptlang.org/docs/handbook/esm-node.html) 관련 설정이 pakage.json에 누락이 되어서 작동이 안되는 것 같습니다. 해당 문제를 해결한 버전을 곧바로 배포할 수 있도록 하겠습니다.

**Comment by JaeSeoKim** [comment]
추가적으로 next.js 13 feature인 appDir 지원을 위한 `"use client"` 키워드 추가 작업도 진행하겠습니다.

**Comment by choijeongon** [comment]
배포 되면 알려주시면 감사하겠습니다!

**Comment by JaeSeoKim** [comment]
@choijeongon 현재 현역 군인인 상황이라 ㅠ 작업을 진행 못하고 있었습니다. 양해 부탁드립니다. 오늘 저녁 중으로 작업하여 배포하겠습니다.

**Comment by JaeSeoKim** [comment]
@

> 추가적으로 next.js 13 feature인 appDir 지원을 위한 `"use client"` 키워드 추가 작업도 진행하겠습니다.

해당 작업은 bundler 교체 작업을 진행해야 하기 때문에, 시간 소요가 필요할 것 같습니다.
아래와 같이 임시로 사용하시면 됩니다.

```tsx
// KakaoMaps.tsx
"use client"
export * from "react-kakao-maps-sdk"
export type * from "react-kakao-maps-sdk"
```

**Comment by JaeSeoKim** [comment]
@choijeongon  [v1.1.12](https://www.npmjs.com/package/react-kakao-maps-sdk/v/1.1.12) 배포하였습니다.

**Comment by choijeongon** [comment]
감사합니다!!
