### ISSUE TITLE
MarkerClusterer 사용시 마커가 사라지는 문제

### ISSUE THREAD

**Issue by itjustbong** [JaeSeoKim/react-kakao-maps-sdk#55]
아래와 같이 사용하면 마커가 잘 보이는데,
```
{장소데이터.map((loc) => (
          <MapMarker
            key={loc.id}
            position={{
              lat: loc.latitude,
              lng: loc.longitude,
            }}
          />
 ))}
```
![스크린샷 2023-08-22 오후 5 50 35](https://github.com/JaeSeoKim/react-kakao-maps-sdk/assets/29947261/8b627b24-0c42-4847-8859-100494466a70)

마커 클러스터를 활용하면 마커가 사라집니다..ㅠㅠ
```
      <MarkerClusterer
        averageCenter={true} // 클러스터에 포함된 마커들의 평균 위치를 클러스터 마커 위치로 설정
        minLevel={2} // 클러스터 할 최소 지도 레벨
      >
        {장소데이터.map((loc) => (
          <MapMarker
            key={loc.id}
            position={{
              lat: loc.latitude,
              lng: loc.longitude,
            }}
          />
        ))}
      </MarkerClusterer>
```
![스크린샷 2023-08-22 오후 5 50 15](https://github.com/JaeSeoKim/react-kakao-maps-sdk/assets/29947261/6c83f781-65d6-4439-af29-a72069135cc9)

제가 잘 못 사용한 것인지 모르겠으나 클러스터링 마커가 보이지 않아 이슈에 남겨둡니다.
감사합니다.

**Comment by JaeSeoKim** [comment]
해당 현상을 재현할 수 있는 코드를 CodeSandBox 와 같은 web IDE로 공유받을 수 있을까요?

**Comment by itjustbong** [comment]
> IDE

빠른 회신 감사드립니다.
https://codesandbox.io/p/sandbox/intelligent-lumiere-h4tcqd
해당 링크에 동일한 문제가 있습니다!
확인 부탁드리겠습니다 !

**Comment by JaeSeoKim** [comment]
@itjustbong markercluster를 사용하기 위해서는 kakaomap load 사용할 라이브러리를 명시해야 합니다.
참고: https://apis.map.kakao.com/web/guide/#loadlibrary

**Comment by JaeSeoKim** [comment]
다음버전에 해당 라이브러리를 로딩 하지 않고 해당 컴포넌트를 호출시 에러를 발생할 수 있도록 처리 하겠습니다.!

**Comment by itjustbong** [comment]
> 다음버전에 해당 라이브러리를 로딩 하지 않고 해당 컴포넌트를 호출시 에러를 발생할 수 있도록 처리 하겠습니다.!

@JaeSeoKim 
허걱 해당 부분을 명시해야하는지 모르고 있었네요!!!
사용법? 혹은 sample 부분에 간략히 추가해야하는 스크립트 명시만 해줘도 좋을 것 같습니다.

빠른 회신과 해결법(?) 알려주셔서 감사드립니다!!!
