### ISSUE TITLE
여러개 마커 표시하기 관련 오류 TypeError: this.T.vd is not a function

### ISSUE THREAD

**Issue by ohda00** [JaeSeoKim/react-kakao-maps-sdk#56]
안녕하세요~ 먼저 정말 간편하고 유용한 라이브러리를 만들어주셔서 감사합니다~!

맵을 활용한 프로젝트를 앞두고 있었는데, 이 라이브러리를 발견하고 정말 기뻤습니다.

그런데, 여러개 마커 표시하기 관련 오류가 TypeError: this.T.vd is not a function 나고 있습니다...

홈페이지 예시 결과에서도 동일한 오류가 뜨던데요. 

다른 이미지로 마커 생성하기 에서도 같은 오류가 납니다. 

확인해주시면 감사하겠습니다.

https://react-kakao-maps-sdk.jaeseokim.dev/docs/sample/overlay/basicMarkerImage
https://react-kakao-maps-sdk.jaeseokim.dev/docs/sample/overlay/multipleMarkerImage

**Comment by JaeSeoKim** [comment]
현재 현역 군 복무중에 있어, 답변이 늦어질 수 있습니다. 양해 부탁드립니다.

번들링 사이즈를 줄이면서 코드를 제대로 검증하지 않고 수정한 탓에 문제가 발생한 것 같습니다 ㅠㅠ(E2E 테스트 작업을 추가해야할 것 같네요 ㅠㅠ)

오늘 군대에서 휴가를 복귀하는 날이여서, 빠르면 오늘 늦어도 내일까지 수정해서 배포하도록하겠습니다.

**Comment by JaeSeoKim** [comment]
npm에 [v1.1.16](https://www.npmjs.com/package/react-kakao-maps-sdk/v/1.1.16)으로 배포 완료되었습니다.!
한번 확인 부탁드립니다.!
