### ISSUE TITLE
Type error: 'Map' cannot be used as a JSX component. 

### ISSUE THREAD

**Issue by in-ch** [JaeSeoKim/react-kakao-maps-sdk#57]
```
Type error: 'Map' cannot be used as a JSX component.
  Its return type 'ReactNode' is not a valid JSX element.
    Type 'string' is not assignable to type 'ReactElement<any, any>'.
```

next.js 프로젝트에서 빌드 시 다음과 같은 에러가 납니다. 
로컬에서는 잘 작동하는데 ec2 Amazon linux 환경에서 빌드 시 다음과 같은 에러가 나네요... 
혹시 해결 방법이 있을까요? 

node: v18.10.0

**Comment by in-ch** [comment]
fork 받아서 확인해 보니 build 후에 Map 타입이 `React.ForwardRefExoticComponent<
  Omit<MapProps<React.ElementType<any>>, 'ref'> & React.RefAttributes<kakao.maps.Map>
>;`로 되어 있던데 npm에서 다운받아보니 Map.d.ts가 아직 MapComponent로 되어 있는 것 같습니다 !

**Comment by JaeSeoKim** [comment]
현재 현역 군 복무중에 있어, 답변이 늦어질 수 있습니다. 양해 부탁드립니다.

혹시 현재 설치되어 있는 nextjs 버전과 @types/react 버전 그리고 react-kakao-maps-sdk 버전을 알려주실 수 있으실까요?

추가적으로 해당 문제가 발생하는 환경을 codesandbox와 같은 web ide로 구현해주신다면 문제를 파악하는데 도움이 됩니다.!!

**Comment by JaeSeoKim** [comment]
@in-ch v1.1.19-beta를 통해서 해당 문제점을 해결할 수 있는 버전을 배포하였습니다.
문제가 발생하는지 확인이 가능할까요?

https://www.npmjs.com/package/react-kakao-maps-sdk/v/1.1.19-beta

**Comment by in-ch** [comment]
@JaeSeoKim 
답변 늦어서 가능합니다. 해당 버전 빌드 잘됩니다. 
감사합니다. 👍🏼

**Comment by JaeSeoKim** [comment]
@in-ch  [v1.1.19](https://www.npmjs.com/package/react-kakao-maps-sdk/v/1.1.19) 버전 배포 하였습니다.!
