### ISSUE TITLE
useKakaoLoader hook을 사용하면 렌더링 되지 않습니다.

### ISSUE THREAD

**Issue by Dave352** [JaeSeoKim/react-kakao-maps-sdk#58]
먼저 감사의 말씀을 드립니다.
react-kakao-maps-sdk 만들어주셔서 잘 사용하고 있습니다.
감사합니다.

CodeSandBox로 안내해드리고 싶었으나 저도 위와 같은 문제가 발생합니다. #57
실제 레포에서 사용할 때는 위와 같은 문제는 발생하지 않습니다. . 

<hr />

## 사용한 모듈 버전
- 번들러: vite
- react-kakao-maps-sdk : v0.1.14.  => v0.1.16
- kakao.maps.d.ts : v0.1.38

<hr />

## 현상
useInjectKakaoMapApi를 useKakaoLoader로 수정하면 렌더링이 되지 않습니다.
버전을 v0.1.14로 다운그레이드 한 후에 useInjectKakaoMapApi를 사용하면 정상적으로 렌더링됩니다.

**그리고 이건 제 느낌인데, 메모이제이션 버그 같습니다.**

<hr />

## 코드
```typescript
import { Map, useKakaoLoader } from "react-kakao-maps-sdk";

function App() {
  const { loading, error } = useKakaoLoader({
    appkey: import.meta.env.VITE_KAKAO_MAPS_API_KEY,    // ~> 환경변수
  });

  if (error) {
    throw new Error("카카오 API Error");
  }

  if (loading) {
    return <div>kakao loading...</div>;
  }

  return (
    <div>
      <Map
        center={{
          lat: 33.450701,
          lng: 126.570667
        }}
        style={{
          width: "100%",
          height: "450px"
        }}
        level={3}
      />
    </div>
  );
}

export default App;

```

**Comment by Dave352** [comment]
답변 감사합니다. Close 하겠습니다.

**Comment by JaeSeoKim** [comment]
[npm v1.1.17](https://www.npmjs.com/package/react-kakao-maps-sdk/v/1.1.17) 배포 완료 하였습니다.

**Comment by JaeSeoKim** [comment]
@Dave352 CodeSandbox에서 예시를 만들려고 할 때 #57 와 같은 문제가 발생한다고 이야기 주셨는데, 혹시 [v1.1.19-beta](https://www.npmjs.com/package/react-kakao-maps-sdk/v/1.1.19-beta)에서는 어떻게 동작하는지 알 수 있을까요?

**Comment by Dave352** [comment]
@JaeSeoKim 1.1.19-beta 버전은 codesandbox에서 보이지 않습니다. 

![image](https://github.com/JaeSeoKim/react-kakao-maps-sdk/assets/114476531/1cfe076b-8082-4e19-b4f2-157855e22c1d)

<br />

사진은 1.1.18 버전이며,

## 에러
```text
kakao is not a defined
```
<br />

코드는 이렇게 했습니다.

<br />

```typescript
import { useEffect, useMemo, useState } from "react";
import { Loader, LoaderOptions, Map } from "react-kakao-maps-sdk";

function App() {
  const options: LoaderOptions = {
    appkey: ""
  };

  const loader = useMemo(() => {
    return new Loader(options);
  }, [JSON.stringify(options)]);

  const [state, setState] = useState<{
    loading: boolean;
    error: ErrorEvent | undefined;
  }>({
    loading: true,
    error: undefined
  });

  useEffect(() => {
    loader
      .load()
      .then(() => setState({ loading: false, error: undefined }))
      .catch((error) => setState({ error, loading: false }));
  }, [loader]);

  if (state.error) {
    return <div>error...</div>;
  }

  return (
    <Map
      center={{
        lat: 33.450701,
        lng: 126.570667
      }}
      style={{
        width: "100%",
        height: "450px"
      }}
      level={3}
    />
  );
}

export default App;


```

useKakaoLoader로 해도 동일해서 이렇게 해봤습니다.

**Comment by Dave352** [comment]
@JaeSeoKim 

오... 1.1.19-beta 버전에서는 #57 과 같은 문제는 해결되었습니다.
그런데 여전히 맵을 그리진 못하네요.

![image](https://github.com/JaeSeoKim/react-kakao-maps-sdk/assets/114476531/355ab378-d12a-415c-a98c-01d943d38d3c)

**Comment by JaeSeoKim** [comment]
@Dave352  [v1.1.19](https://www.npmjs.com/package/react-kakao-maps-sdk/v/1.1.19) 버전 배포 하면서 해결하였습니다..!
