### ISSUE TITLE
이 라이브러리를 사용하고 영어로 바꿀 수 있을까요? Is it possible to use this library but change the output to english for users?

### ISSUE THREAD

**Issue by coofzilla** [JaeSeoKim/react-kakao-maps-sdk#6]

**Comment by coofzilla** [comment]
지금 님의 라이브러리를 사용하면 왼쪽 사진처럼 출력이 되는데, 저는 오른쪽 사진 처럼 영어로 바꿔서 출력하고 싶어요..한국어 아직 서툴러서 죄송하고 이해할 수 있으면 좋겠습니다 ㅠ
[Screen Shot 2022-02-13 at 3 41 29 PM](https://user-images.githubusercontent.com/75731066/153742373-a4e8ffd0-826a-4990-b8b0-594c80cc0a71.png)

**Comment by JaeSeoKim** [comment]
현재 제가 알고 있기로는 kakaomap의 open api 버전에서는 영문 지도를 제공하지 않아서 힘들 것 같습니다.
만약 변경이 가능한 가이드 문서를 발견하신다면 해당 라이브러리에도 추가 해보도록 할께요!

**Comment by coofzilla** [comment]
그렇군요, 그럼 어쩔 수 없네요, 답변 감사합니다. 미래에는 영어도 추가되면 좋겠네요~ ㅋㅋㅋ
