### ISSUE TITLE
useKakaoLoader 에서 libraries를 동적으로 생성하면 무한 루프에 빠집니다.

### ISSUE THREAD

**Issue by inithink** [JaeSeoKim/react-kakao-maps-sdk#63]
현재 useKakaoLoader는 useEffect 내에 libraries가 변경되면 다시 로더를 부르도록 되어있습니다.
그렇기 때문에 
```typescript
  useKakaoLoader({
    appkey: "ee6d3a8341b76986ba628bf221754319",
    libraries: ["services", "clusterer"],
  });
```
이렇게 사용하면 libraries가 계속 새롭게 생성되기 때문에 무한 루프에 빠집니다.

그래서 
```typescript
let libraries: Libraries = ["services", "clusterer"];

export function Component() {
  useKakaoLoader({
    appkey: "ee6d3a8341b76986ba628bf221754319",
    libraries,
  });
... 
```
이런식으로 상수로 선언이 필요합니다.
문서를 바꾸던지 코드가 바뀌면 좋을거 같습니다 :)

**Comment by JaeSeoKim** [comment]
현재 현역 군복무중에 있어, 테스트가 힘든점 양해드립니다. 현재 간단하게 핸드폰으로 코드 수정후 배포 진행중에 있습니다. v1.1.23에서도 동일한 문제가 발생하는지 확인 가능할까요?

**Comment by JaeSeoKim** [comment]
@inithink https://www.npmjs.com/package/react-kakao-maps-sdk/v/1.1.23

**Comment by inithink** [comment]
잘 동작합니다 :)
