### ISSUE TITLE
Vercel에 배포하면 지도가 보이지 않습니다.

### ISSUE THREAD

**Issue by HA-SEUNG-JEONG** [JaeSeoKim/react-kakao-maps-sdk#69]
vite로 개발하고 있습니다.

https://developers.kakao.com/ 에서 vercel에 배포한 주소로 사이트도메인 추가했고,  `index.html`에서는 appKey를 JavaScript 키로 사용하고 있으며, 다음과 같이 작성하였습니다.

```html
<script
            type="text/javascript"
            src="//dapi.kakao.com/v2/maps/sdk.js?appkey=JavaScript 키&libraries=services,clusterer"
        ></script>


```

![스크린샷 2023-12-12 오후 9 47 35](https://github.com/JaeSeoKim/react-kakao-maps-sdk/assets/88266129/bcbfeed4-ca95-44e7-b769-2eed29875a46)

**Comment by JaeSeoKim** [comment]
해당 라이브러리는 kakao Map Sdk를 React로 사용하기 편하게 랩핑한 라이브러리 입니다. 라이브러리 관련 인증 문제는 kakao에 문의해주세요.

추가로 이야기 드리자면 401응답으로 보아 인증키가 잘못되었거나, 웹사이트를 잘못 등록한 것 같습니다.
