### ISSUE TITLE
웹 접근성을 위한 지도내에 aria 속성추가

### ISSUE THREAD

**Issue by soparifly** [JaeSeoKim/react-kakao-maps-sdk#70]
```jsx
  <Map // 지도를 표시할 Container
    aria-label="지도"
    id="map"
    center={{
      // 지도의 중심좌표
      lat: Number(currentAddress[0].y),
      lng: Number(currentAddress[0].x),
    }}
    style={{
      // 지도의 크기
      width: "100%",
      height: "350px",
    }}
    level={3} // 지도의 확대 레벨
  >
    <MapMarker
      aria-label="지도"
      position={{
        lat: Number(currentAddress[0].y),
        lng: Number(currentAddress[0].x),
      }}
    />
  </Map>
```

웹 접근성 인증을 위한 지도 태그내에 area  누락 문제가 있습니다 
Map과 marker에 속성을 추가했으나 동일합니다
혹시 다른방법이 있나요?

**Comment by JaeSeoKim** [comment]
확인해보겠습니다.! 잠시만 기달려주세요!

**Comment by soparifly** [comment]
지도만 사용할경우 area 속성이 추가되어있습니다 하지만 마커가 추가될경우 이슈가 있습니다

**Comment by JaeSeoKim** [comment]
`Map` 컴포넌트의 경우 `map` 이 생성되는 `dom`에 대해서 저희가 제어하고 있기 때문에 정상적으로 전달이 가능합니다.
https://github.com/JaeSeoKim/react-kakao-maps-sdk/blob/main/packages/react-kakao-maps-sdk/src/components/Map.tsx#L394

<img width="1461" alt="image" src="https://github.com/JaeSeoKim/react-kakao-maps-sdk/assets/48559454/23ce557d-cf67-429b-8ffb-de8a9a1325c8">

다만 `Marker`의 경우 `kakao-maps` 에서 제공하는 sdk를 이용하여 단순 호출하고 있기 때문에 `aria-*` 와 같은 태그를 전달할 수 없습니다.

만약 해당 `aria-*` 태그가 전달되는 `Marker` 만들고 싶은 경우, `kakao` 측에게 문의를 하거나, `CustomOverlay` 를 이용하여 직접 `Marker`를 만드는 것을 제안 드립니다.

https://react-kakao-maps-sdk.jaeseokim.dev/docs/sample/overlay/customOverlay1

**Comment by JaeSeoKim** [comment]
참고: `Marker` 컴포넌트 내부에서 `marker` 생성하는 로직

https://github.com/JaeSeoKim/react-kakao-maps-sdk/blob/main/packages/react-kakao-maps-sdk/src/components/Marker.tsx#L225-L240

**Comment by JaeSeoKim** [comment]
가독성을 위해 원본 이슈 본문을 일부 수정하였습니다.!

**Comment by soparifly** [comment]
확인했습니다! 공식문서에 나와있는 내용과 혼합하여 

제공해주신 MapMarker에 Image 속성을 제공하고 alt 키값을 적용하면 문제가 해결됩니다!

훌륭한 라이브러리를 제공해주셔서 감사해요 땡큐

 <MapMarker
            image={{
              src: "https://i1.daumcdn.net/dmaps/apis/n_local_blit_04.png",
              size: {
                width: 40,
                height: 40,
              },
              options: {
                alt: "마커 이미지",
              },
            }}
            position={{
              lat: Number(currentAddress[0].y),
              lng: Number(currentAddress[0].x),
            }}
          />

**Comment by JaeSeoKim** [comment]
좋은 의견 감사합니다.! `alt` 옵션이 있다는 것을 생각하지 못하였네요.!

**Comment by JaeSeoKim** [comment]
@soparifly  `title` 속성을 이용하여도 가능합니다.!
