### ISSUE TITLE
다큐멘테이션 사이트 샘플 페이지 오류

### ISSUE THREAD

**Issue by reedfim** [JaeSeoKim/react-kakao-maps-sdk#72]
안녕하세요~
React로 포팅된 SDK를 제공해 주셔서 매우 감사드립니다.

다른이 아니라, 샘플페이지에서, 
"라이브러리" 쪽을 보면 

"키워드로 검색하기 부터, 클러스터 마커에 텍스트 표기하기"는 문제가 없으나,
drawing 라이브러리 샘플 부터는 오류가 발생합니다.

이 원인을 확인해보니,

페이지를 최초 접속할때(또는 새로고침) drawing 라이브러리 쪽 샘플들은 kakao,service,drawing,cluster 파일들을 추가로딩을 못하는 것으로 보입니다.

이외 다른 샘플은 문제가 없는 것으로 보이구요.

한번 확인 부탁드립니다.

**Comment by JaeSeoKim** [comment]
제보 감사합니다! service,drawing,cluster 파일들을 정상적으로 로딩은 진행하였으나, 기존 코드에서는 로딩 되기 이전에 `DrawingManager`의 `drawingMode`에게 전달하는 값들이 로딩이후에 접근해야 하지만, 로딩 이전에 접근해서 문제가 발생하였습니다.
로딩 이전에 접근할 수 있는 방법으로, 정적인 값을 넣는 기능은 넣어두었으나 문서에는 반영하지 않아서 문제가 생겼네요..!

제보 감사합니다!

**Comment by JaeSeoKim** [comment]
https://react-kakao-maps-sdk.jaeseokim.dev/docs/sample/library/basicDrawingLibrary/

접근하시면 정상적으로 동작하시는 것을 확인할 수 있습니다.!
