### ISSUE TITLE
next 14버전 인포윈도우가 안떠요 ㅜ

### ISSUE THREAD

**Issue by opjt** [JaeSeoKim/react-kakao-maps-sdk#73]
"next": "14.2.3" 버전 사용하고있는데 인포윈도우나 커스텀오버레이가 뜨지를 않습니다
![image](https://github.com/JaeSeoKim/react-kakao-maps-sdk/assets/57663597/d583cba7-865b-40d4-9181-589eaa3be017)
사진처럼 나오네요 
13버전에서는 정상작동합니다

```ts
"use client"

import { Map, MapMarker, useKakaoLoader } from "react-kakao-maps-sdk"

export default function KakaoMap() {
  const { error } = useKakaoLoader({
    appkey: process.env.NEXT_PUBLIC_APPKEY!, // 발급 받은 APPKEY
    // ...options,
  })
  if (error) return <div>Error</div>
  return (
    <Map
      center={{ lat: 33.5563, lng: 126.79581 }}
      style={{ width: "100%", height: "360px" }}
    >
      <MapMarker position={{ lat: 33.55635, lng: 126.795841 }}>
        <div style={{ color: "#000" }}>Hello World!</div>
      </MapMarker>
    </Map>
  )
}

```
코드는 올려주신 next example 안에 있는 코드 사용하였습니다

**Comment by JaeSeoKim** [comment]
회사를 다니게 되어서 해당 이슈가 발생한지 모르고 있었네요.

**Comment by JaeSeoKim** [comment]
정확한 원인은 분석이 되지 않았지만, 내부적으로 kakao에게 전달하는 domElement 객체를 useRef를 통해 사전에 생성하고 전달하는데 이렇게 생성된 객체를 kakao에서 받는 경우에 내부적으로 가지고는 있지만, 정상적으로 dom에 반영하지 않는 버그? 오류? 증상을 확인하였습니다.

따라서, 내부 코드를 kakao 객체에게 전달하는 시점에 생성하고 kakao 객체를 통해 전달한 content를 받아 렌더링 하는 형태로 버그를 수정하였습니다.

**Comment by JaeSeoKim** [comment]
[v1.1.27](https://github.com/JaeSeoKim/react-kakao-maps-sdk/releases/tag/v1.1.27)으로 배포 완료되었습니다.

**Comment by JaeSeoKim** [comment]
문제가 추가로 발생한다면 이야기해주세요.!
