### ISSUE TITLE
[ts] geocoder 추가 메서드 type 구현

### ISSUE THREAD

**Issue by ziponia** [JaeSeoKim/react-kakao-maps-sdk#8]
https://github.com/JaeSeoKim/kakao.maps.d.ts/blob/master/%40types/services.d.ts#L26

Gecoder 타입 중, 다음 method 가 구현되어야 합니다.

- [x] addressSearch
- [x] coord2Address
- [x] coord2RegionCode
- [x] transCoord

다음 문서를 확인하십시오 [https://apis.map.kakao.com/web/documentation/#services_Geocoder_Methods](https://apis.map.kakao.com/web/documentation/#services_Geocoder_Methods)

노고에 감사합니다.

**Comment by JaeSeoKim** [comment]
해당 타입 추가 작성 반영하도록 하겠습니다.
감사합니다~!

**Comment by JaeSeoKim** [comment]
type 작성 추가 완료. https://github.com/JaeSeoKim/kakao.maps.d.ts/tree/v0.1.25

**Comment by JaeSeoKim** [comment]
최신 버전의 type를 사용하도록 Bump 하였습니다.!

https://github.com/JaeSeoKim/react-kakao-maps-sdk/releases/tag/v1.0.5
